//DOM calls
const deleteRecipeButton = document.getElementById('deleteRecipeButton')
const titleText = document.getElementById('titles')
const ingredientsList = document.getElementById('ingredients-list')
const ingredientsDiv = document.querySelector('#ingredients')
const appendedDiv = document.getElementById('ingredientsList')
const appendedDiv2 = document.getElementById('directions')
const directionsList = document.getElementById('steps')
const steps = document.getElementById('steps-form')
const notes = document.getElementById('notes')
